name: 'CI'

on:
  - pull_request

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: v18.14.0

      - name: Check ESLint
        run: yarn lint

      - name: Check Prettier
        run: yarn prettier:check
